Write a function so that the columns of the output matrix are powers of the input vector.

In [9]:
import numpy as np
x=np.array([1,2,3,4,5,6])
N=5
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix)

[[   1    1    1    1    1]
 [  16    8    4    2    1]
 [  81   27    9    3    1]
 [ 256   64   16    4    1]
 [ 625  125   25    5    1]
 [1296  216   36    6    1]]


In [10]:
def move_avg_value(mylist, N):
    cumsum, moving_aves = [0], []
    for i, x in enumerate(mylist, 1):
        cumsum.append(cumsum[i-1] + x) 
        if i>=N:
            moving_ave = round(((cumsum[i] - cumsum[i-N])/N),2) 
            moving_aves.append(moving_ave) 
    print("Moving average values list: ", moving_aves)
    print("Length of the list l-N+1: ", len(moving_aves))

In [11]:
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 3

move_avg_value(mylist,N)

Moving average values list:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of the list l-N+1:  11
